### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by osfx** [PrintYard/Liberia#1]
## add

- [rrr](#)

```
app:
  version: 1.0.1
  title: "OSOM"
  components:
    - ggg
    - cvgh
    - Ghent
```
### task 

- [ ] [Task one](https://github.com/PrintYard/Liberia/issues/2)
- [x] [Task three ](https://github.com/PrintYard/Liberia/issues/3)
- [x] [Forty two ](https://github.com/PrintYard/Liberia/issues/4)
